### ISSUE TITLE
put request behavior

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder-server#3]
While testing the server, I found out that a put request returns the updated vehicle with a 200 in its response, but the put request for Commodities returns a 204. We should get rid of this inconsistency and make sure that the API document follows it. Which way should put requests behave?

**Comment by grovecj** [comment]
From Mozilla:
![Successful PUT should return 201](https://raw.githubusercontent.com/CSSE497/pathfinder/gh-pages/images/mozilla-put-status-code.PNG)

**Comment by danhanson** [comment]
That's not right, models shouldn't be created when doing an update so we shouldn't return the created code. That picture you have refers to put requests in the general case, our case is using put requests to implement a CRUD API. This link http://www.restapitutorial.com/lessons/httpmethods.html says that it should either return status 204(No Content) or 200(OK) depending on whether it returns anything. We should determine whether the request should return the updated model or not. Keep in mind that depending on which one we pick may make it easier or harder to work on the client SDKs that use the API.

**Comment by aj-michael** [comment]
@grovecj @danhanson Did we resolve this? What is the current state of our codebase? Can we close this issue?

**Comment by grovecj** [comment]
No. Dan's code still returns the modified object and mine returns 204

**Comment by grovecj** [comment]
Ok, we are officially taking a vote. @danhanson @aj-michael @robinsdm 

| Team Member | 200 or 204? | Why? |
| --- | --- | --- |
| Carter | 204 | If a user is updating the cvc model, the output they are interested in is a new route. Also, if a user is using PUT to update vehicle/commodity location every few seconds, then we may end up using quite a bit of bandwidth |
| Adam | Whichever is easier to code. | The client libraries will never use this endpoint, they will only use web sockets. |
| Dan | 200 | It would be more consistent since the other methods return the object |
| David | 204 | Less bandwidth and developers do not need to see what the object was updated to and if they want to see it they can just use a get request. |

**Comment by danhanson** [comment]
lets compromise and return a 202

**Comment by aj-michael** [comment]
I'm honestly impressed that everyone filled out that table.

**Comment by grovecj** [comment]
Despite david and I having the majority, adam wins

**Comment by robinsdm** [comment]
Adams answer didn't even pick a side.

**Comment by grovecj** [comment]
204
